apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: NodePort
  selector:
    app: {{ .Values.appName }}
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007
      protocol: TCP
  
