apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-init-config
data:
  db-load-script.sql: |
    CREATE DATABASE IF NOT EXISTS myapp_db;
    USE myapp_db;
    CREATE TABLE IF NOT EXISTS products (
        id INT AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(255) NOT NULL,
        price DECIMAL(10, 2) NOT NULL,
        description TEXT
    );
    INSERT INTO products (name, price, description) VALUES
    ('Product 1', 19.99, 'Description for product 1'),
    ('Product 2', 29.99, 'Description for product 2'),
    ('Product 3', 39.99, 'Description for product 3');
